version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "04:00"
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: "@swydo/custom-integrations"
    versions:
    - 1.0.195
    - 1.0.199
    - 1.0.202
    - 1.0.203
    - 1.0.205
    - 1.0.211
    - 1.0.215
    - 1.0.219
    - 1.0.224
    - 1.0.228
    - 1.0.232
    - 1.0.234
    - 1.0.240
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.9
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: standard-version
    versions:
    - 9.1.0
  - dependency-name: object-path
    versions:
    - 0.11.5
