version: 2.1

executors:
  nodejs_v10:
    resource_class: small
    docker:
      - image: circleci/node:10

commands:
  restore_build_cache:
    description: Restore build cache
    steps:
      - restore_cache:
          keys:
           - dependency-cache-v0-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
           - dependency-cache-v0-
  setup_git:
    description: Setup swybot git username + email
    steps:
      - run:
          name: Setup git
          command: |
            git config --global user.name SwyBot
            git config --global user.email SwyBot@users.noreply.github.com

jobs:
  build:
    executor: nodejs_v10
    steps:
      - checkout
      - restore_build_cache
      - run:
          name: Install node modules
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-v0-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    executor: nodejs_v10
    steps:
      - checkout
      - restore_build_cache
      - run:
          name: Run lint
          command: |
            npm run eslint -s
      - run:
          name: Run mocha
          command: |
            npm run mocha -s
      - run:
          name: Check coverage
          command: |
            npm run coverage-check -s
            npm run coverage-report -s
  release:
    executor: nodejs_v10
    steps:
      - checkout
      - restore_build_cache
      - setup_git
      - run:
          name: Release
          command: |
            npm run release
            git push --follow-tags origin master

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
